version: '3.8'

services:
  flask-chat-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY=your_access_key
      - AWS_SECRET_KEY=your_secret_key
      - AWS_REGION=your_region
      - FLASK_ENV=development
