version: '3.8'

services:
  flask-chat-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    secrets:
      - aws_access_key
      - aws_secret_key
      - aws_region

secrets:
  aws_access_key:
    external: true
  aws_secret_key:
    external: true
  aws_region:
    external: true
